image: maven:3.9.6-eclipse-temurin-21

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

cache:
  paths:
    - .m2/

tests:
  stage: test
  script:
    - mvn clean test -Dheadless=true
  artifacts:
    when: always
    paths:
      - screenshots/
    expire_in: 7 days
    artifacts:
      when: always
      paths:
        - screenshots/
        - target/surefire-reports/

