image: maven:3.9.6-eclipse-temurin-21

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

playwright-tests:
  stage: test
  script:
    - mvn clean test -Dheadless=true
  artifacts:
    when: always
    paths:
      - target/surefire-reports
      - screenshots
      - target/allure-results
    expire_in: 7 days
